### ISSUE TITLE
Support Vectorized Icons

### ISSUE THREAD

**Issue by HeikoKlare** [vi-eclipse/Eclipse-Platform#1]
Eclipse only supports rasterized icons and uses conventions for providing higher-resolution versions (adding `@2x` to the file name). In order to improve icon quality with different DPI settings, vectorized graphics representing icons (`.svg`) shall be supported.

There has already been some work/discussion on that topic: https://bugs.eclipse.org/bugs/show_bug.cgi?id=568215

### Includes
- [x] #290

### Follow-Up Work
- [x] https://github.com/eclipse-pde/eclipse.pde/issues/1722
- [x] Create https://github.com/eclipse-platform/eclipse.platform.images/issues/129
- [x] Remove icons added to actual bundles from images repository [agreement in community call](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/wiki/Eclipse-IDE-%E2%80%90-Developers-Community-Call#24th-april-2025): \
https://github.com/eclipse-platform/eclipse.platform.images/issues/152

**Comment by fedejeanne** [comment]
cc @jakub-suliga
