### ISSUE TITLE
Findings in test session (17.12.2024)

### ISSUE THREAD

**Issue by fedejeanne** [vi-eclipse/Eclipse-Platform#162]
# Objective
- Find bugs when **rescaling at runtime** is active

# Setup
- Tested on the I-BUILD **I20241216-1800**: https://download.eclipse.org/eclipse/downloads/drops4/I20241216-1800/download.php?dropFile=eclipse-SDK-I20241216-1800-win32-x86_64.zip

# Raw findings
These findings need to be processed an turned into proper tickets. 

## Federico

- Primary 100% left, Secondary 175% right

1. [x] Start Eclipse in 100% monitor and change the zoom to 175% -> looks odd ([Screenshot](https://github.com/user-attachments/assets/813b03a7-cd67-4963-949b-c6dee35bd574))
2. [x] https://github.com/eclipse-platform/eclipse.platform.swt/issues/557
3. [ ] eclipse-platform/eclipse.platform.swt#184 
4. [x] Preferences: [Text](https://github.com/user-attachments/assets/cc522d74-61fc-44f3-afe4-df137cef2a41) and [Buttons](https://github.com/user-attachments/assets/360d446c-9729-4b0d-b184-8dbd8fdfd8f4)

  - Open the Preferences > Editor > Save Actions
  - Change DPIs around, both of the current monitor and the other one --> The UI refreshes and the size changes but buttons and other UI elements look Odd. Probably related to @ShahzaibIbrahim's
 issue nr. "S2"

5. [x] https://github.com/eclipse-platform/eclipse.platform.ui/issues/2759

**Edge**
1. [x] Welcome page can't navigate back:
	-Open the welcome page > Tutorials > "Create a Hello World application" --> It navigates to a new page.
	- Click on "Restore Welcome" --> It doesn't go back
	- This is NOT reproducible on my Eclipse IDE (Build id: I20241216-1800)
	
2. [x] JavaDoc: [Video](https://github.com/user-attachments/assets/312e332f-952d-4c47-8062-1d357d597073)

	- Start Eclipse on 175% secondary monitor
	- Hover over a class to show its JavaDoc and move the mouse into it --> it vanishes

3. [ ] https://github.com/eclipse-platform/eclipse.platform.swt/issues/1730

## Marty
Configuration: Right (Primary) 100%, Left 175 %, left to left 100%
- ~~The ide on right, drag the editor out and hover at the edge where left and left to left meet, there's a jump in the rectangle~~ (Fixed by using the multi zoom coordinate system mapper)
![Recording2024-12-17140314-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/961e91ca-e238-4546-b7ae-bd382f19c138)

- [x] #175
![image](https://github.com/user-attachments/assets/7dbe9b53-fbfa-4136-8820-3708cc2c1f71)

- [ ] eclipse-platform/eclipse.platform.swt#178
![image](https://github.com/user-attachments/assets/96ee6850-f282-48ee-8c57-6d0ee0db8a91)

- [x] eclipse-platform/eclipse.platform.swt#176
![image](https://github.com/user-attachments/assets/82ce9b3f-4ad9-40bf-905c-0baad29d3262)

- [x] eclipse-platform/eclipse.platform.swt#177
![image](https://github.com/user-attachments/assets/227eca2d-b008-46c4-b83c-23f7f889ebb2)

- [ ] Button scaling not done wrt the content inside: start refactor > move on 175 and move to 100, the scaling is bad
dragging an editor from 175% to 100% creates scaled up editor
![image](https://github.com/user-attachments/assets/c52c44cf-2c41-45b1-a28e-b135240e019c)

## Shahzaib
S1) Moving from Secondary (200) to Primary (150)  Project -> Properties -> Save actions.  the text area is not scaling ( also with project -> properties -> Clean Up)
https://github.com/vi-eclipse/Eclipse-Platform/issues/168
S2) Moving from Secondary (200) to Primary (150)  Project -> Properties -> Save actions. buttons (text scaling but not the button layout)
https://github.com/vi-eclipse/Eclipse-Platform/issues/165
<img width="687" alt="image" src="https://github.com/user-attachments/assets/ff01e2b6-70d5-4efa-9151-26673cafeb06" />
S3) Moving from Secondary (200) to Primary (150)  Help - > Show Context Help -> Images not scaled or aligned
![image](https://github.com/user-attachments/assets/f7d7cc4b-b786-4553-9ca2-4dfb846f4240)
https://github.com/vi-eclipse/Eclipse-Platform/issues/169
S4) On 200% monitor. When removing the conditional breakpoint, the dialog has a message for "Do not show this message again" cutoff. (Checked only in dark theme for now)
https://github.com/vi-eclipse/Eclipse-Platform/issues/170

![image](https://github.com/user-attachments/assets/8c045b9a-e2ba-499b-9df0-d0fcbe095bb9)

**Comment by HeikoKlare** [comment]
Have individual issues already been created for all the findings? Otherwise we should probably convert all the finding in issues and link the issues here to see that everything is covered by a dedicated issue.

**Comment by ShahzaibIbrahim** [comment]
@HeikoKlare I have linked mine

**Comment by fedejeanne** [comment]
Tip: If you add the "[ ]" to the items (in _edit_ mode) then you can _Convert them to issues_

![image](https://github.com/user-attachments/assets/0e7973cd-ee15-4bea-abe5-1cf12ae9d436)

**Comment by HeikoKlare** [comment]
@fedejeanne are your findings already documented in explicit issues?

**Comment by HeikoKlare** [comment]
Closing this one as to my knowledge all findings have been converted into separate tickets.
